# @package _group_
_target_: alphazero.network.policies.make_policy # targets a function
representation_dim: ??? # set later
action_dim: ??? # set later
action_bound: ??? # set later
distribution: "normal" # normal or beta
num_components: 2 # uses a GMM if num_components > 1
hidden_dimensions: [128, 128, 128]
nonlinearity: "elu" # any of relu, leakyrelu, relu6, elu, silu/swish, hardswish
layernorm: false
log_param_min: -5
log_param_max: 2